### ISSUE TITLE
undefined method regression in f5a89b1abbf31dd42f3bb4fe05e14c02f69b0de8

### ISSUE THREAD

**Issue by markjenkinsskullspace** [datacommons/stonesoup#6]
f5a89b1abbf31dd42f3bb4fe05e14c02f69b0de8 introduces a regression where attempting to run the development server I get:

```
Processing SearchController#index (for 127.0.0.1 at 2014-06-26 19:10:18) [GET]

NoMethodError (undefined method `country_filter' for #<DefaultSite:0x7f674cb32b70>):
app/controllers/application_controller.rb:63:in `set_custom_filters'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:95:in `start'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `each'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `start'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:23:in `start'
~/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:82:in `start'

Rendered rescues/_trace (18.8ms)
Rendered rescues/_request_and_response (0.9ms)
Rendering rescues/layout (internal_server_error)
```

I determined that particular revision caused the regression by using git bisect

I'm using rvm on Ubuntu 12.04 to use 
ruby 1.8.7 (2014-01-28 patchlevel 376) [x86_64-linux]
rubygems 1.8.29

And my gems (installed with bundle install) are:
bundler (1.6.3)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
fastercsv (1.5.5)
ferret (0.11.8.5)
gem-wrappers (1.2.5)
geokit (1.6.7)
json (1.8.1)
multi_json (1.9.0)
mysql (2.9.1)
rack (1.1.6)
rake (10.1.1, 0.9.2.2)
rdoc (4.1.1)
rdoc-data (4.0.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
